
// 02_Draw.cpp : 定义应用程序的类行为。
//

#include "stdafx.h"
#include "afxwinappex.h"
#include "afxdialogex.h"
#include "00_Draw.h"
#include "MainFrm.h"

#include "00_DrawDoc.h"
#include "00_DrawView.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif


// CMy02_DrawApp

BEGIN_MESSAGE_MAP(CMy02_DrawApp, CWinAppEx)
	ON_COMMAND(ID_APP_ABOUT, &CMy02_DrawApp::OnAppAbout)
	// File-based standard documentation commands
	ON_COMMAND(ID_FILE_NEW, &CWinAppEx::OnFileNew)
	ON_COMMAND(ID_FILE_OPEN, &CWinAppEx::OnFileOpen)
	// Standard print setup commands
	ON_COMMAND(ID_FILE_PRINT_SETUP, &CWinAppEx::OnFilePrintSetup)
END_MESSAGE_MAP()


// CMy02_DrawApp constructor

CMy02_DrawApp::CMy02_DrawApp()
{
	// Support restart manager
	m_dwRestartManagerSupportFlags = AFX_RESTART_MANAGER_SUPPORT_ALL_ASPECTS;
#ifdef _MANAGED
	// If the application is built with common language runtime support (/clr), then:
// 1) This additional setting is required for "Restart Manager" support to work properly.
// 2) In your project, you must add references to System.Windows.Forms in build order.
	System::Windows::Forms::Application::SetUnhandledExceptionMode(System::Windows::Forms::UnhandledExceptionMode::ThrowException);
#endif

	
	//为 CompanyName.ProductName.SubProduct.VersionInformation
	SetAppID(_T("02_Draw.AppID.NoVersion"));

}

CMy02_DrawApp theApp;


BOOL CMy02_DrawApp::InitInstance()
{
	// If an application running on Windows XP manifest specifies
// Use ComCtl32.dll version 6 or higher to enable visual mode,
//You need InitCommonControlsEx(). Otherwise, the window will not be created.
	INITCOMMONCONTROLSEX InitCtrls;
	InitCtrls.dwSize = sizeof(InitCtrls);
	// Set this to include all the
//Public control class.
	InitCtrls.dwICC = ICC_WIN95_CLASSES;
	InitCommonControlsEx(&InitCtrls);

	CWinAppEx::InitInstance();


	// initial OLE 
	if (!AfxOleInit())
	{
		AfxMessageBox(IDP_OLE_INIT_FAILED);
		return FALSE;
	}

	AfxEnableControlContainer();

	EnableTaskbarInteraction(FALSE);

	// Using the RichEdit control requires AfxInitRichEdit2()
	// AfxInitRichEdit2();

	// standard initialization
	// If these functions are not used and wish to reduce
	// The size of the final executable file, the following should be removed
	// No specific initialization routine required
	//Change the registry key used to store settings
	// TODO: The string should be modified appropriately,
	// For example, change it to the company or organization name
	SetRegistryKey(_T("Native application generated by application wizard"));
	LoadStdProfileSettings(4);  // Load standard INI file options (including MRU)


	// Register the application's document template. Document template
	// Will be used as a connection between the document, frame window and view
	CSingleDocTemplate* pDocTemplate;
	pDocTemplate = new CSingleDocTemplate(
		IDR_MAINFRAME,
		RUNTIME_CLASS(CMy02_DrawDoc),
		RUNTIME_CLASS(CMainFrame),       // main SDI frame
		RUNTIME_CLASS(CMy02_DrawView));
	if (!pDocTemplate)
		return FALSE;
	AddDocTemplate(pDocTemplate);


	// Analyze command lines for standard shell commands, DDE, and open file operations
	CCommandLineInfo cmdInfo;
	ParseCommandLine(cmdInfo);



	// Schedule the command specified on the command line. if
// Returns FALSE if the application is started with /RegServer, /Register, /Unregserver or /Unregister.
	if (!ProcessShellCommand(cmdInfo))
		return FALSE;

	// The only window is initialized, so show it and update it
	m_pMainWnd->ShowWindow(SW_SHOW);
	m_pMainWnd->UpdateWindow();
	return TRUE;
}

int CMy02_DrawApp::ExitInstance()
{
	//TODO:  Handle additional resources that may have been added
	AfxOleTerm(FALSE);

	return CWinAppEx::ExitInstance();
}

// CMy02_DrawApp message handler
// CAboutDlg dialog for the application's About menu item

class CAboutDlg : public CDialogEx
{
public:
	CAboutDlg();

// dialog data
	enum { IDD = IDD_ABOUTBOX };

protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support

// impl
protected:
	DECLARE_MESSAGE_MAP()
};

CAboutDlg::CAboutDlg() : CDialogEx(CAboutDlg::IDD)
{
}

void CAboutDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialogEx::DoDataExchange(pDX);
}

BEGIN_MESSAGE_MAP(CAboutDlg, CDialogEx)
END_MESSAGE_MAP()

// Application command for running dialog box
void CMy02_DrawApp::OnAppAbout()
{
	CAboutDlg aboutDlg;
	aboutDlg.DoModal();
}




